# Generated by Django 4.0.3 on 2022-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citing_paper_doi', models.CharField(blank=True, db_column='citing_paper_DOI', max_length=100, null=True)),
                ('cited_paper_doi', models.CharField(blank=True, max_length=100, null=True)),
                ('outline', models.CharField(blank=True, max_length=300, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citation_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citing_paper_doi', models.CharField(db_column='citing_paper_DOI', max_length=100)),
                ('original_outline', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_outline', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'outline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('doi', models.CharField(db_column='DOI', max_length=200, primary_key=True, serialize=False)),
                ('article_title', models.CharField(blank=True, db_column='article-title', max_length=200, null=True)),
                ('journal_title', models.CharField(blank=True, db_column='journal-title', max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('volume', models.CharField(blank=True, max_length=45, null=True)),
                ('issue', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
    ]
